# Generated by Django 5.2.4 on 2025-07-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_public', models.BooleanField(default=True)),
                ('availability', models.CharField(choices=[('Weekends', 'Weekends'), ('Evenings', 'Evenings'), ('Mornings', 'Mornings')], max_length=50)),
                ('skills_offered', models.TextField(help_text='Comma-separated list')),
                ('skills_wanted', models.TextField(help_text='Comma-separated list')),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
