# Generated by Django 5.2.4 on 2025-07-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_skillprofile_rating_skillprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillswaprequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='skillprofile',
            name='availability',
            field=models.CharField(choices=[('Weekends', 'Weekends'), ('Evenings', 'Evenings'), ('Mornings', 'Mornings')], max_length=50),
        ),
    ]
