# Generated by Django 5.2.4 on 2025-07-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_skillswaprequest_allow_general_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillswaprequest',
            name='allow_general',
            field=models.BooleanField(default=True),
        ),
    ]
